
-- The view 'AvailableCars' provides quick access to information about all available cars in the dealership.
-- It combines data from the 'Cars' and 'Inventories' tables to display key information about each car whose status is marked as 'Available'.
-- Usage of the view: SELECT * FROM AvailableCars;
CREATE VIEW AvailableCars AS
SELECT Cars.VIN, Cars.Brand, Cars.Model, Cars.YearOfManufacture, Inventories.Status, Inventories.Price
FROM dbo.Cars
JOIN dbo.Inventories ON Cars.VIN = Inventories.VIN
WHERE Inventories.Status = 'Available';


-- The 'SalesProfitByEmployee' view is intended for analyzing the sales performance of employees.
-- Its purpose is to calculate the total sales profit generated by each employee.
-- A simple algorithm is based on the difference between the selling price and the purchase price of the vehicle.
-- Usage of the view: SELECT * FROM SalesProfitByEmployee; 
CREATE OR ALTER VIEW SalesProfitByEmployee AS
SELECT 
    e.EmployeeID,
    e.FirstName,
    e.LastName,
    SUM(s.SalePrice - i.AcquisitionPrice) AS TotalProfit
FROM dbo.Sales s
JOIN dbo.Employees e ON s.EmployeeID = e.EmployeeID
JOIN dbo.Inventories i ON s.VIN = i.VIN
WHERE i.Status = 'Sold' -- An additional condition is added to consider only sold vehicles.
GROUP BY e.EmployeeID, e.FirstName, e.LastName;
